### ISSUE TITLE
Add Cocopods support?

### ISSUE THREAD

**Issue by hollyoops** [ra1028/SwiftUI-Hooks#18]
Hi Team,

 Is there any plan to add cocopods support?

**Comment by ra1028** [comment]
@hollyoops 
Sorry but I've chosen not to support CocoaPods due to the cost to maintain pods for all OSS projects.
If it's definitely not possible to use SPM, you can add a local podspec in your project or fork this repository to maintain it yourself.

**Comment by hollyoops** [comment]
Thank you,  I did that. So the name of `Hooks` has been taken by me. If you might want to support CocoaPods in the future. You can use other name.

By the way, I built a State Management Library `RecoilSwift` for SwiftUI based on your hook library, So thank you bring this lib out.  😉

https://github.com/hollyoops/RecoilSwift

**Comment by ra1028** [comment]
Interesting. I'm actually developing a recoil like architecture library too 😉
