### ISSUE TITLE
[Bug]:  The package product 'Hooks' cannot be used as a dependency of this target because it uses unsafe build flags.

### ISSUE THREAD

**Issue by GodL** [ra1028/SwiftUI-Hooks#23]
### Checklist

- [X] This is not a bug caused by platform.
- [X] Reviewed the README and documentation.
- [X] Checked existing issues & PRs to ensure not duplicated.

### What happened?

This error is reported after importing in Xcode

### Expected Behavior

This package uses unSafeFlag

### Reproduction Steps

1. xcode import this package
2. build

### Swift Version

v5

### Library Version

lastest

**Comment by strangeliu** [comment]
same here

**Comment by ra1028** [comment]
@GodL @strangeliu 
Thanks for reporting. That will be fixed in the next release.
Fix PR: https://github.com/ra1028/swiftui-hooks/pull/24

**Comment by ra1028** [comment]
Released the new version [0.0.6](https://github.com/ra1028/swiftui-hooks/releases/tag/0.0.6)

Feel free to reopen this issue if you will face related issues.
