### ISSUE TITLE
[Feat Request]: Add support for lazy creation of initial state in useState hook

### ISSUE THREAD

**Issue by josefdolezal** [ra1028/SwiftUI-Hooks#27]
### Checklist

- [X] Reviewed the README and documentation.
- [X] Checked existing issues & PRs to ensure not duplicated.

### Description

The signature of `useState` hook in v0.0.7 looks like this:

```swift
func useState<State>(_ : State) -> Binding<State>
```

This works fine for basic usage (eg. `useState(0)` or `useState(myConstant)`), but might cause a **decrease in app performance** when used with "factory" method:

```swift
useState(generateMyInitialState())
```

Although the `generateMyInitialState` function should not be performance heavy not even for a single call (it runs on main thread), there might be use-cases where a **single call** to performance heavier "factory method" is acceptable sacrifice.

The React implementation offers additional overload of the `useState` hook allowing user to pass a factory method for initial state, rather than initial state itself. A swift alternative could be translated to:

```swift
func useState<State>(_ initialState: @escaping () -> State) -> Binding<State>
```

and used as:

```swift
useState({ generateMyInitialState() })

// -- OR --

useState(generateMyInitialState)
```

I would like open a discussion about implementing such feature.

### Example Use Case

Consider reading a database value used as an initial state for a view. A developer might be tempted to write code like this:

```swift
HookScope {
  let database = useDatabase()
  let myEntity = useState(database.fetchEntity())
  ...
}
```

This might work flawlessly for a small project, but easily becomes problematic when the project grows (eg. deep navigation stack, modals, ...).

To mitigate the problem, user has to explicitly memoize the generated initial state:

```swift
HookScop {
  let database = useDatabase()
  let initialState = useMemo(.once) {
    database.fetchEntity()
  }
  let myEntity = useState(initialState)
  ...
}
```

This is a simple workaround/fix, but it's easy to forget about. More over, it might be **counter-intuitive** for newcomers (considering the `useState` will only use the generated state once, but generates it on each view render).

### Alternative Solution

As a solution, I'd like to introduce new API, which should address both intuitiveness and performance of the state hook.

## Option 1

The simplest solution is to introduce new `useState` overload, which would take "factory method" as a parameter and utilise `useMemo` hook internally:

```swift
func useState<State>(_ initialState: @escaping () -> State) -> Binding<State> {
  let state = useMemo(.once) { initialState() }

  return useState(state)
}

// Usage:
useState(generateMyInitialState())    // Without optimisation (Same behavior as v0.0.7)
useState { generateMyInitialState() } // With optimisation (New API)
useState(generateMyInitialState)      // With optimisation (New API - Short syntax)
```

### Pros

* Source-compatible with existing code
* Gives user ability to choose between optimised and unoptimised overload

### Cons

* Introduces dependency on `useMemo` hook
* Optimisation **is not** first class citizen of the hook (`StateHook` class)
* Requires the user to know the difference between overloads (unintuitive)

## Option 2

Replace existing `useState` hook with new signature:

```swift
func useState<State>(_ initialState: @escaping () -> State) -> Binding<State>

// Usage

useState { generateMyInitialState() } // Optimised - New API
useState(generateMyInitialState)      // Optimised - New API with short syntax
```

Update `StateHook` to support lazy state initialisation:

```diff
private struct StateHook<State>: Hook {
-   let initialState: State
+   let initialState: () -> State
    ...
    func makeState() -> Ref {
-       Ref(initialState: initialState)
+       Ref(initialState: initialState())
    }
    ...
}
```

Optionally, support backwards compatibility by creating `useState` overload accepting state constant:

```swift
func useState<State>(_ initialState: State) -> Binding<State> {
    return useState({ initialState }) // Fallbacks to implementation above
}
```

### Pros

* (optionally) Source-compatible with existing code
* Gives user ability to choose between optimised and unoptimised overload
* Optimisation **is** first class citizen of the hook (`StateHook` class)

### Cons

* Requires the user to know the difference between overloads (unintuitive)

## Option 3

Builds on top of `StateHook` changes from Option 2, but replaces the closure with `@autoclosure` argument:

```swift
func useState<State>(_ initialState: @escaping @autoclosure () -> State) -> Binding<State>

// Usage

useState(0)                        // Old API (No performance impact for constants)
useState(generateMyInitialState()) // New API (Optimised to single call of `generateMyInitialState`)
```

This allows user to use existing syntax, but leverage improved performance for free.

### Pros

* Source-compatible with existing code, with performance improvements applied automatically
* Optimisation **is** first class citizen of the hook (`StateHook` class)
* Uses Swift-native feature to achieve laziness with compact syntax

### Cons

* Some edge-cases might behave differently than in v0.0.7 (see below)
* Does not match React syntax

<details><summary>Incompatible edge cases</summary>

Consider following code, using a side effect while generating initial state:

```swift
var numberOfCalls = 0

func generateState() -> String {
    numberOfCalls += 1
    return ""
}

func App() -> some View {
    HookScope {
        let state = useState(generateState())
        ...
    }
}
```

When re-rendering the view 3 times, the value of `numberOfCalls` will differ between v0.0.7 (4 - initial + 3 re-renders) and new API (1 - initial). This might cause an issue in theory, but I consider it highly unlikely, considering there is other API for running side effects.

In addition, the user is able to replicate v0.0.7 behavior with new API like this:

```diff
- let state = useState(generateState())
+ let generatedState = generateState()
+ let state = useState(generatedState)
```

</details>

### Proposed Solution

Considering all the options above, I would vote for implementing Option 3, as it offers nice & compact syntax and automatically applies optimisation to existing code.

**Comment by ra1028** [comment]
@josefdolezal 

Thanks for the proposal with a clear description! It totally makes sense to me.
I voted for option3 for a glance but after looking at your description, I would vote for option2, because:

- A bit more intuitive compared to using @/autoclosure.
- 100% source-compatible. I don't seek source compat that much as it's v0.0.7 as of now, but also it's much better if it is.
- It matches with React syntax. This library tends to be preferred by engineers who mainly do web dev.

In terms of the downside for overloads, I don't think it's a big deal because it works intuitively even when user doesn't know there's overload version. 
My only concern is whether or not it falls to a wrong type inference with an edge-case syntax like below.

```swift
let value = useState { 100 } 
// value is closure () -> Int
```

**Comment by josefdolezal** [comment]
Swift is smart enough to infer correct type - it always chooses the most specific matching type when there are multiple overloads.

```swift
let closure: () -> Int = { 100 }
useState(closure)
// Matches exactly argument type of `() -> State`

let closure2: (Int) -> Int = { _ in 100 }
useState(closure2)
// Matches exactly argument type of `State`
```

Anyway, when you pass closure to the hook, the actual state type depends on implementation:

| `useState { 100 }` | `State` Type | Note |
|---|---|---|
| **0.0.7** | `() -> Int` | |
| **Option 3** | `() -> Int` | Matches current implementation |
| **Option 2** | `Int` | Would need to be `useState { { 100 } }` to match current implementation |

I just realised that Option 2 is not 100% the same as current implementation for all cases, but I don't think storing closures in state is a good practice anyway, so I would be surprised if this change actually affected anyone.

**Comment by ra1028** [comment]
Agreed.
I think we now agree that we are going with option2.

**Comment by josefdolezal** [comment]
Alright, I'll draft a PR and we can move the discussion there 👍🏾
